openapi: 3.0.0
info:
  description: API for mesh communication backend
  version: 1.0.3
  title: MeshCommunication API

paths:
  /devices:
    get:
      summary: gets all devices
      operationId: getAllDevices
      description: 
        "Returns all devices present in the mesh network."

      responses:
        200:
          description: "Success: Received all devices"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
        400:
          description: "Bad Request"
        204:
          description: "No devices found"
        500:
          description: "Internal Server Error"

  /devices/{status}:
    get:
      summary: gets devices by status
      operationId: getDevicesByStatus
      description: 
        "Returns devices present in the mesh network with the given status."

      parameters:
        - in: path
          name: status
          description: "What type of devices to retrieve"
          schema:
            type: string
            enum:
              - all
              - failed
              - operational
          required: true

      responses:
        200:
          description: "Success: Received all devices"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
        400:
          description: "Bad Request"
        204:
          description: "No devices found"
        500:
          description: "Internal Server Error"

  /device/{id}:
    get:
      summary: gets a specific device
      operationId: getDevice
      description: 
        "Returns devices present in the mesh network with the given id."

      parameters:
        - in: path
          name: id
          description: "Id of the device to retrieve"
          schema:
            type: integer
          required: true

      responses:
        200:
          description: "Success: Received all devices"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        404:
          description: "Device does not exist."
        500:
          description: "Internal Server Error"

  /devices/inrange/all:
    get:
      summary: gets devices within range of another device
      operationId: getDevicesInRange
      description: 
        "For each device in the mesh network, returns devices that are in range to it."

      responses:
        200:
          description: "Success: Received all devices within range"
          content:
            application/json:
              schema:
                description: "Dictionary with device ids as keys, and arrays of devices as values. Each key maps to an array of all devices that are in range of the device with the same id as the key."
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/Device'
              example:
                1:
                  - device_id: 1
                    battery_level: 68
                    battery_max: 100
                    position:
                      x: 2
                      y: 1
                      z: 4
                  - device_id: 4
                    battery_level: 23
                    battery_max: 100
                    position:
                      x: 5
                      y: 2
                      z: 6
                23:
                  - device_id: 13
                    battery_level: 45
                    battery_max: 120
                    position:
                      x: 5
                      y: 6
                      z: 7

        204:
          description: "No devices found"

        500:
          description: "Internal Server Error"

  /devices/inrange/{id}:
    get:
      summary: gets devices within range of another device
      operationId: getDevicesInRangeWithId
      description: 
        "Returns devices present in the mesh network that are within range of a device with the given id."

      parameters:
        - in: path
          name: id
          description: "Id of the device to make the search on"
          schema:
            type: integer
          required: true

      responses:
        200:
          description: "Success: Received all devices within range"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'

        204:
          description: "No devices in range found"

        404:
          description: "Device does not exist."
          
        500:
          description: "Internal Server Error"


  /tick/{time_flow}:
    post:
      summary: Update grid ticks
      operationId: position
      description: "Path that updates the grid by given number of ticks."
      parameters:
        - in: path
          name: time_flow
          description: "In what direction time will advance"
          schema:
            type: string
            enum:
              - forwards
              - backwards
          required: true
        - in: query
          name: n_ticks
          description: "Number of ticks to skip"
          required: false
          schema:
            type: integer
            default: 1

      responses:
        200:
          description: "Mesh Grid updated"
        404:
          description: "Device does not exist."

  /orchestrate:
    post:
      summary: Make orchestrator send messages to the network
      operationId: orchestrate
      description: "Path that signals orchestrator to send messages for each product in the layout file."

      responses:
        200:
          description: "Orchestrator orchestrated"


  /message/send:
    get:
      summary: Get all messages of type send in the current tick
      operationId: getAllMessagesSend
      description:
        "Path that returns, for all message senders of the current tick, the messages of type `send` that were sent by them."
      responses:
        200:
          description: "Success: Received all messages"
          content:
            application/json:
              schema:
                description: "Dictionary with ids of devices that sent message as keys, and arrays of messages as values. Each key maps to an array of messages that correspond to send commands that were sent by the device which id is the same as the array's key."
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/SendMessage'
              example:
                54:
                  - hop: 68
                    final: 30
                  - hop: 21
                    final: 45
                4:
                  - hop: 54
                    final: 2
                  - hop: 2
                    final: 1
        500:
          description: "Internal Server Error"

  /message/receive:
    get:
      summary: Get all messages of type receive in the current tick
      operationId: getAllMessagesReceive
      description:
        "Path that returns, for all message senders of the current tick, the messages of type `receive` that were sent by them."
      responses:
        200:
          description: "Success: Received all messages"
          content:
            application/json:
              schema:
                description: "Dictionary with ids of devices that sent message as keys, and arrays of messages as values. Each key maps to an array of messages that correspond to receive commands that were sent by the device which id is the same as the array's key."
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/ReceiveMessage'
              example:
                1:
                  - hop: 68
                    final: 30
                    failed: true
                  - hop: 21
                    final: 45
                    failed: false
                30:
                  - hop: 54
                    final: 2
                    failed: false
                  - hop: 2
                    final: 1
                    failed: false
        500:
          description: "Internal Server Error"

  /log:
    get:
      summary: Get logs of the current tick
      operationId: getLog
      description:
        "Path that returns, for all devices that had a log in the current tick, their respective log messages."
      responses:
        200:
          description: "Success: Received all logs"
          content:
            application/json:
              schema:
                description: "Dictionary in which its keys are the devices, and its values are arrays of message logs that were sent by its respective key/sender"
                type: object
                additionalProperties:
                  type: array
                  items:
                    description: "Message log"
                    type: string
              example:
                Device 6:
                  - "Received message: [source=0], [msg=padoru], [lastHop=0]"
                  - "Relaying message: [destination=8], [msg=padoru]"
  /metrics:
    get:
      summary: Gets metrics with which the communication is evaluated
      operationId: getMetrics
      description:
        "Path that returns, for the whole communication, a collection of metrics for the current tick."
      responses:
        200:
          description: "Success: Received all metrics"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metrics'
              example:
                batTick: 10
                batCommunication: 20
                failed: 0
                ticks: 2

  /restart:
    post:
      summary: Restart simulation
      operationId: restart
      description: 
        "Path that restarts the simulation"
      responses:
        200:
          description: "Success: Restarted simulation"
        500:
          description: "Internal Server Error"

  /layout:
    post:
      summary: Use a specified layout
      operationId: specifyLayout

      requestBody:
        description: The layout to use
        required: true
        content:
          application/json:
            schema:
              description: "Dictionary with ids of devices as keys and its respective position as value."
              type: object
              additionalProperties:
                type: array
                items:
                  $ref: '#/components/schemas/Position'
            example:
              1:
                - x: 1
                  y: 2
                  z: 3
              0:
                - x: 7
                  y: 4
                  z: -3

      description: 
        "Path that changes the current layout"
      responses:
        200:
          description: "Success: Changed the layout"
components:
  schemas:
    SendMessage:
      type: object
      properties:
        final:
          description: "ID of the final destination of the message"
          type: integer
        hop:
          description: "ID of the device to receive the message on this hop"
          type: integer

    ReceiveMessage:
      type: object
      properties:
        final:
          description: "ID of the final destination of the message"
          type: integer
        hop:
          description: "ID of the device to receive the message on this hop"
          type: integer
        failed:
          description: "Wether or not the message was lost in the current tick"
          type: boolean

    Metrics:
      type: object
      properties:
        batTick:
          description: "Battery consumed in the last tick"
          type: integer
        batCommunication:
          description: "Battery consumed in the whole communication"
          type: integer
        failed:
          description: "Number of failures that happened in the system"
          type: integer
        ticks:
          description: "Number of tick since the beginning of the communication"
          type: integer

    Device:
      allOf:
        - type: object
          properties:
            id:
              type: integer
            battery_level:
              type: integer
            battery_max:
              type: integer
            position:
              $ref: '#/components/schemas/Position'

    Position:
      type: object

      properties:
        x:
          type: integer
        y: 
          type: integer
        z:
          type: integer
      example:
        x: 2
        y: 1
        z: -5
